import 'dart:convert';

import 'package:coconut_vault/packages/bc-ur-dart/lib/ur_decoder.dart';
import 'package:coconut_vault/utils/bb_qr/bb_qr_decoder.dart';
import 'package:coconut_vault/utils/ur_bytes_converter.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('Coordinator Decoder(sparrow export option)', () {
    test('[Coldcard] 단일 BBQR(Unicode)을 올바르게 파싱하는지 테스트', () {
      final bbqrParts = [
        "B\$ZU0100IXG4XMU2GAAIBYJ5J6IZTM5QLWURAEO5QWVXHAAMAIU6ULQIZBCQQYFYHZ63W2FH7P7Z73YLNDWJ2PDJT4AHO6HT4JJ3ZQBH4VBQXMXCTWBB7TZ6UU6E2QF4QCQKK7OPU2P4FF4ANGOZ4QP5O4IALD55RPTXEBRCMAMZABB55WFZD4UCGV72ELKUG3N72ZV33NWMLDLAWK7KN7AMHQYQULUCOCKLJA4OO3UAY6B3YS5HSOJFV52UYF25LHB5QI7G4D2FNLJNBEPOONC7OBBG55RXXJRGLBXUAFFZSPB2FNVTVM6XEHXBMGX6WLWHQNFCAPSJ7UILNWI3AIGWWS67O7KXBIGROU7IJB7PIMHS6QVKBHJJVNULP6ZH34SL2UE3KNEJW5UYMYR45VGMMO7M4M3LTB6NYVU2THAXWJ4KQENVQ6IPK4TXOVJTRBB76WE2RUJ6HJA3XFBZMIKA64FJNPRSAYKOMYVNOSHLZTQTQHY53WCPK2WZWAUSKTIVBD774VFYSZPURDZUO4VYZC35ZDMQLUZK2OPVE5JMUH4XF43TXLFQORA7I3VYQZS26RER4RLTKP6NUNDUESL5XGSFI3FPEYIB5K4V5UN6VJV4LIROYM4VWYMYVO5IEPBXUFL6AM",
      ];

      final decoder = BbQrDecoder();

      // 각 조각을 받아서 처리
      for (final part in bbqrParts) {
        final received = decoder.receivePart(part);
        expect(received, true, reason: '조각이 올바르게 수신되어야 함: $part');
      }

      // 완성 여부 확인
      expect(decoder.isComplete, true, reason: '모든 조각이 모이면 완성되어야 함');
      expect(decoder.expectedTotal, 1, reason: '총 1개의 조각이 있어야 함');
      expect(decoder.receivedCount, 1, reason: '1개의 조각이 수신되어야 함');
      expect(decoder.progress, 1.0, reason: '진행률이 100%여야 함');

      // 디코딩 결과 확인
      print('=== BBQR 디코딩 결과 ===');
      final resultText = decoder.getCombinedText();
      print(resultText);
      print('========================');
    });

    test('[BSMS] 단일 UR:BYTES를 올바르게 파싱하는지 테스트', () {
      final urParts = [
        'UR:BYTES/HKADKNCNCXGRIHKKJKJYJLJTIHCXGTKPJZJYINJKINIOCXJKIHJYKPJOCXIYINJZIHCXDEIAJPIHHSJYIHIECXIDKKCXGUJOHSJPJPJLKTDTBKCNBKGLHSJNIHFTCXJEIHKKJKJYJLJTDPJNKPJZJYINJKINIOBKGDJLJZINIAKKFTCXEYCXJLIYCXEYBKFYIHJPINKOHSJYINJLJTFTCXJNDLEEETDIDLDYDIDLDYDIDLEYDIBKFGJLJPJNHSJYFTCXGDEYHGGUFDBKBKFPEOFWEYFEFWEMDYFTCXKSJOKPIDENFEESJYENIHGYFLINGHHFGHFLESESKSHGJLENGRFEIEHKFPHFKKFLJYJPJNJEFXGLIOIDGHGDHFGDGUFEKOFPENKTIOFPGUEYINJPHTKSGSIEKOIDGSFWGHKNECHDGOGMJYGSGUFWEYGSGDGTHTFDIYETECFXGEKSHSJOIOJPETGLJOHKIAIEFYHDECENGOGRJOHFKOHTECJSKSKPESJEBKFPDYFGENFWFPDYDYFTCXKSJOKPIDENFYJYIAETIHIHENFPGDHSETEMHFFWKKEMGSJLHTJLENGMIYIEFLHKEOJEETIOJTGDKNGHEHGHHKKOFDKKIOHFGDGEISKPJPEYEEGMIOFEJEESFGIYJYJOKNIAKOGDISGYIOJEESIMECHGGRJPECIMJEKSJKEHGSISIHKTEYECIYIYGLECJYGSGYIYJEIAIEFEENGSKNECFYJLJKJTJKGHBKDAKPIDTT',
      ];
      final decoder = URDecoder();
      int receivedCount = 0;
      for (final part in urParts) {
        final received = decoder.receivePart(part);
        if (received) {
          receivedCount++;
        }
        print('조각 수신: $received, 진행률: ${decoder.estimatedPercentComplete() * 100}%');
      }

      // 완성 여부 확인
      expect(decoder.isComplete(), true, reason: '모든 조각이 모이면 완성되어야 함');
      expect(decoder.isSuccess(), true, reason: '디코딩이 성공해야 함');

      // 디코딩 결과 text를 기대함
      print('=== UR 디코딩 결과 ===');
      final textResult = UrBytesConverter.convertToText(decoder.result);
      print(textResult);
      print('========================');
    });

    test('[BSMS/Keystone Multisig] UR:BYTES 조각을 올바르게 파싱하는지 테스트', () {
      final urParts = [
        'UR:BYTES/1453-2/LPCFAHPMAOCFADWTCYNNLENDVLHDYAEHIERFDTHSKGCNGWEHECHEHYHEAEESAHCFCMDPECEHGHIECYDICYGSDKFPAYCFCFBGHDJNADBBDIATDKBKENIECMCTIODSATEOFNAOAAEEJLJZCHGUFHGUHEENKTJKDRCACKFZBWFHADDRJOGSAXBTETFRGHBWKEGLKBFWCLAOGYFEKBAYDYBDCEDACXDPAOHPAAISCSCWKEGOBNGWCAHHCTHYKEBYGOGEGDHEJPBTDNDEGDAXKIGTBBJYHLBGKGFDETJPJSJYAHKBHSFYEHGWFWDYENDPDRDMAYKBKSFMAHBGDWADGSBNBACPFNDLATBBBTCTCNEHDTGHEHFZEHDKFZBDDECEAECMDLADEOAHKKASBEDLHSFSKKDKCALBBEIAJNINFLCXBTCMBGAEFEBBHSCYFWFRAMCFAXDPJKDTDSDEAOADAEFXCSBNFHIHDAGUCSBKDIASFTBBLBAODACWHKCFDABSBDAMAXFSIYDIDPBDGWAOWLGRDP',
        'UR:BYTES/1452-2/LPCFAHPSAOCFADWTCYNNLENDVLHDYAISIHGYBKFPDYFGENFWFPDYDYFTCXJYJOKPIDFYFGHDEOFYINFWJTESGHHSJTJOKPKTKSFEIDIYFWIYGDJLGMFYJYIYFLKPKTGMGLJOJEFXFGIYEEHKJSEYEYGUGTGUFLISJPEEKNGSISGTFWFGGUIDGHGMEMIMFGJTGSIDGLIEJSKOJYGSGOKKKPGUFPHKJEEEIMGMETKOGUHSEEISEYJNETJSGSENKNKSKTGOEEIDHKFEEHKTFLJNFYFGBKFPEOFWEYFEFWEMDYFTCXJYJOKPIDFYFGHDFDIMGLENFPHTIDISHTIEECFDENHDISGTHGFPGRIMJLFXJTESJPESGOIMENJKGTJYKKHDGRGHJEGLEOFDFPHSHKFEGTFEFLGRKNGOETEOENIOJEKSIAFGEMGDGOGHEOFWIOGTGOIMETGRGDJNGOEEEEEMJEKNJLEHJTHSGTIHJYJEKKHGGLGMJLFWHSJOIYFPIDJSHGJSGOKPKNGYBKPTCPBAHT',
        'UR:BYTES/1453-2/LPCFAHPMAOCFADWTCYNNLENDVLHDYAEHIERFDTHSKGCNGWEHECHEHYHEAEESAHCFCMDPECEHGHIECYDICYGSDKFPAYCFCFBGHDJNADBBDIATDKBKENIECMCTIODSATEOFNAOAAEEJLJZCHGUFHGUHEENKTJKDRCACKFZBWFHADDRJOGSAXBTETFRGHBWKEGLKBFWCLAOGYFEKBAYDYBDCEDACXDPAOHPAAISCSCWKEGOBNGWCAHHCTHYKEBYGOGEGDHEJPBTDNDEGDAXKIGTBBJYHLBGKGFDETJPJSJYAHKBHSFYEHGWFWDYENDPDRDMAYKBKSFMAHBGDWADGSBNBACPFNDLATBBBTCTCNEHDTGHEHFZEHDKFZBDDECEAECMDLADEOAHKKASBEDLHSFSKKDKCALBBEIAJNINFLCXBTCMBGAEFEBBHSCYFWFRAMCFAXDPJKDTDSDEAOADAEFXCSBNFHIHDAGUCSBKDIASFTBBLBAODACWHKCFDABSBDAMAXFSIYDIDPBDGWAOWLGRDP',
        'UR:BYTES/1454-2/LPCFAHPLAOCFADWTCYNNLENDVLHDYAISIHGYBKFPDYFGENFWFPDYDYFTCXJYJOKPIDFYFGHDEOFYINFWJTESGHHSJTJOKPKTKSFEIDIYFWIYGDJLGMFYJYIYFLKPKTGMGLJOJEFXFGIYEEHKJSEYEYGUGTGUFLISJPEEKNGSISGTFWFGGUIDGHGMEMIMFGJTGSIDGLIEJSKOJYGSGOKKKPGUFPHKJEEEIMGMETKOGUHSEEISEYJNETJSGSENKNKSKTGOEEIDHKFEEHKTFLJNFYFGBKFPEOFWEYFEFWEMDYFTCXJYJOKPIDFYFGHDFDIMGLENFPHTIDISHTIEECFDENHDISGTHGFPGRIMJLFXJTESJPESGOIMENJKGTJYKKHDGRGHJEGLEOFDFPHSHKFEGTFEFLGRKNGOETEOENIOJEKSIAFGEMGDGOGHEOFWIOGTGOIMETGRGDJNGOEEEEEMJEKNJLEHJTHSGTIHJYJEKKHGGLGMJLFWHSJOIYFPIDJSHGJSGOKPKNGYBKGDQDSNMW',
        'UR:BYTES/1455-2/LPCFAHPEAOCFADWTCYNNLENDVLHDYAEHIERFDTHSKGCNGWEHECHEHYHEAEESAHCFCMDPECEHGHIECYDICYGSDKFPAYCFCFBGHDJNADBBDIATDKBKENIECMCTIODSATEOFNAOAAEEJLJZCHGUFHGUHEENKTJKDRCACKFZBWFHADDRJOGSAXBTETFRGHBWKEGLKBFWCLAOGYFEKBAYDYBDCEDACXDPAOHPAAISCSCWKEGOBNGWCAHHCTHYKEBYGOGEGDHEJPBTDNDEGDAXKIGTBBJYHLBGKGFDETJPJSJYAHKBHSFYEHGWFWDYENDPDRDMAYKBKSFMAHBGDWADGSBNBACPFNDLATBBBTCTCNEHDTGHEHFZEHDKFZBDDECEAECMDLADEOAHKKASBEDLHSFSKKDKCALBBEIAJNINFLCXBTCMBGAEFEBBHSCYFWFRAMCFAXDPJKDTDSDEAOADAEFXCSBNFHIHDAGUCSBKDIASFTBBLBAODACWHKCFDABSBDAMAXFSIYDIDPBDGWZOKSLOVL',
        'UR:BYTES/1456-2/LPCFAHPFAOCFADWTCYNNLENDVLHDYAHKADWECNCXGRIHKKJKJYJLJTIHCXGTKPJZJYINJKINIOCXJKIHJYKPJOCXIYINJZIHCXDEIAJPIHHSJYIHIECXIDKKCXGUJOHSJPJPJLKTDTBKCNBKGLHSJNIHFTCXJNKPJZJYINJKINIOEYBKGDJLJZINIAKKFTCXEYCXJLIYCXEOBKFYIHJPINKOHSJYINJLJTFTCXJNDLEEETDIDLEHDIDLDYDIDLEYDIBKFGJLJPJNHSJYFTCXGDEYHGGUFDBKBKEMEOFXECFYFPDYFPFTCXJYJOKPIDFYFGFDESIEIOKNKOIHKKFYETKNGHIDGDGOFGKPGSJPFLJNFXKKIEGLKOKSIHISKKGLIEGOHDGRGEFPGYGLETKSEEHSHTEEIMENGOHTJSFLIYJTJSFGJPFYEEGLJSKKHSGHHFFLGRIDKOFEHGECEEJYJKKOGDGHGREYGOJLGUIDFXFXEHGDGEHKETINFXGLINKTGHGSEOGMHGHTFEJTONPKTL',
        'UR:BYTES/1457-2/LPCFAHPAAOCFADWTCYNNLENDVLHDYAISIHGYBKFPDYFGENFWFPDYDYFTCXJYJOKPIDFYFGHDEOFYINFWJTESGHHSJTJOKPKTKSFEIDIYFWIYGDJLGMFYJYIYFLKPKTGMGLJOJEFXFGIYEEHKJSEYEYGUGTGUFLISJPEEKNGSISGTFWFGGUIDGHGMEMIMFGJTGSIDGLIEJSKOJYGSGOKKKPGUFPHKJEEEIMGMETKOGUHSEEISEYJNETJSGSENKNKSKTGOEEIDHKFEEHKTFLJNFYFGBKFPEOFWEYFEFWEMDYFTCXJYJOKPIDFYFGHDFDIMGLENFPHTIDISHTIEECFDENHDISGTHGFPGRIMJLFXJTESJPESGOIMENJKGTJYKKHDGRGHJEGLEOFDFPHSHKFEGTFEFLGRKNGOETEOENIOJEKSIAFGEMGDGOGHEOFWIOGTGOIMETGRGDJNGOEEEEEMJEKNJLEHJTHSGTIHJYJEKKHGGLGMJLFWHSJOIYFPIDJSHGJSGOKPKNGYBKBNHGIMPL',
        'UR:BYTES/1458-2/LPCFAHPRAOCFADWTCYNNLENDVLHDYAEHIERFDTHSKGCNGWEHECHEHYHEAEESAHCFCMDPECEHGHIECYDICYGSDKFPAYCFCFBGHDJNADBBDIATDKBKENIECMCTIODSATEOFNAOAAEEJLJZCHGUFHGUHEENKTJKDRCACKFZBWFHADDRJOGSAXBTETFRGHBWKEGLKBFWCLAOGYFEKBAYDYBDCEDACXDPAOHPAAISCSCWKEGOBNGWCAHHCTHYKEBYGOGEGDHEJPBTDNDEGDAXKIGTBBJYHLBGKGFDETJPJSJYAHKBHSFYEHGWFWDYENDPDRDMAYKBKSFMAHBGDWADGSBNBACPFNDLATBBBTCTCNEHDTGHEHFZEHDKFZBDDECEAECMDLADEOAHKKASBEDLHSFSKKDKCALBBEIAJNINFLCXBTCMBGAEFEBBHSCYFWFRAMCFAXDPJKDTDSDEAOADAEFXCSBNFHIHDAGUCSBKDIASFTBBLBAODACWHKCFDABSBDAMAXFSIYDIDPBDGWHYBTWPCH',
        'UR:BYTES/1459-2/LPCFAHQDAOCFADWTCYNNLENDVLHDYAHKADWECNCXGRIHKKJKJYJLJTIHCXGTKPJZJYINJKINIOCXJKIHJYKPJOCXIYINJZIHCXDEIAJPIHHSJYIHIECXIDKKCXGUJOHSJPJPJLKTDTBKCNBKGLHSJNIHFTCXJNKPJZJYINJKINIOEYBKGDJLJZINIAKKFTCXEYCXJLIYCXEOBKFYIHJPINKOHSJYINJLJTFTCXJNDLEEETDIDLEHDIDLDYDIDLEYDIBKFGJLJPJNHSJYFTCXGDEYHGGUFDBKBKEMEOFXECFYFPDYFPFTCXJYJOKPIDFYFGFDESIEIOKNKOIHKKFYETKNGHIDGDGOFGKPGSJPFLJNFXKKIEGLKOKSIHISKKGLIEGOHDGRGEFPGYGLETKSEEHSHTEEIMENGOHTJSFLIYJTJSFGJPFYEEGLJSKKHSGHHFFLGRIDKOFEHGECEEJYJKKOGDGHGREYGOJLGUIDFXFXEHGDGEHKETINFXGLINKTGHGSEOGMHGHTFEWMZTLOZT',
        'UR:BYTES/1460-2/LPCFAHQZAOCFADWTCYNNLENDVLHDYAISIHGYBKFPDYFGENFWFPDYDYFTCXJYJOKPIDFYFGHDEOFYINFWJTESGHHSJTJOKPKTKSFEIDIYFWIYGDJLGMFYJYIYFLKPKTGMGLJOJEFXFGIYEEHKJSEYEYGUGTGUFLISJPEEKNGSISGTFWFGGUIDGHGMEMIMFGJTGSIDGLIEJSKOJYGSGOKKKPGUFPHKJEEEIMGMETKOGUHSEEISEYJNETJSGSENKNKSKTGOEEIDHKFEEHKTFLJNFYFGBKFPEOFWEYFEFWEMDYFTCXJYJOKPIDFYFGHDFDIMGLENFPHTIDISHTIEECFDENHDISGTHGFPGRIMJLFXJTESJPESGOIMENJKGTJYKKHDGRGHJEGLEOFDFPHSHKFEGTFEFLGRKNGOETEOENIOJEKSIAFGEMGDGOGHEOFWIOGTGOIMETGRGDJNGOEEEEEMJEKNJLEHJTHSGTIHJYJEKKHGGLGMJLFWHSJOIYFPIDJSHGJSGOKPKNGYBKHDSNBKMW',
        'UR:BYTES/1461-2/LPCFAHREAOCFADWTCYNNLENDVLHDYAHKADWECNCXGRIHKKJKJYJLJTIHCXGTKPJZJYINJKINIOCXJKIHJYKPJOCXIYINJZIHCXDEIAJPIHHSJYIHIECXIDKKCXGUJOHSJPJPJLKTDTBKCNBKGLHSJNIHFTCXJNKPJZJYINJKINIOEYBKGDJLJZINIAKKFTCXEYCXJLIYCXEOBKFYIHJPINKOHSJYINJLJTFTCXJNDLEEETDIDLEHDIDLDYDIDLEYDIBKFGJLJPJNHSJYFTCXGDEYHGGUFDBKBKEMEOFXECFYFPDYFPFTCXJYJOKPIDFYFGFDESIEIOKNKOIHKKFYETKNGHIDGDGOFGKPGSJPFLJNFXKKIEGLKOKSIHISKKGLIEGOHDGRGEFPGYGLETKSEEHSHTEEIMENGOHTJSFLIYJTJSFGJPFYEEGLJSKKHSGHHFFLGRIDKOFEHGECEEJYJKKOGDGHGREYGOJLGUIDFXFXEHGDGEHKETINFXGLINKTGHGSEOGMHGHTFEFTFHSGWS',
        'UR:BYTES/1462-2/LPCFAHRPAOCFADWTCYNNLENDVLHDYAEHIERFDTHSKGCNGWEHECHEHYHEAEESAHCFCMDPECEHGHIECYDICYGSDKFPAYCFCFBGHDJNADBBDIATDKBKENIECMCTIODSATEOFNAOAAEEJLJZCHGUFHGUHEENKTJKDRCACKFZBWFHADDRJOGSAXBTETFRGHBWKEGLKBFWCLAOGYFEKBAYDYBDCEDACXDPAOHPAAISCSCWKEGOBNGWCAHHCTHYKEBYGOGEGDHEJPBTDNDEGDAXKIGTBBJYHLBGKGFDETJPJSJYAHKBHSFYEHGWFWDYENDPDRDMAYKBKSFMAHBGDWADGSBNBACPFNDLATBBBTCTCNEHDTGHEHFZEHDKFZBDDECEAECMDLADEOAHKKASBEDLHSFSKKDKCALBBEIAJNINFLCXBTCMBGAEFEBBHSCYFWFRAMCFAXDPJKDTDSDEAOADAEFXCSBNFHIHDAGUCSBKDIASFTBBLBAODACWHKCFDABSBDAMAXFSIYDIDPBDGWKOHEJNSG',
        'UR:BYTES/1463-2/LPCFAHRLAOCFADWTCYNNLENDVLHDYAISIHGYBKFPDYFGENFWFPDYDYFTCXJYJOKPIDFYFGHDEOFYINFWJTESGHHSJTJOKPKTKSFEIDIYFWIYGDJLGMFYJYIYFLKPKTGMGLJOJEFXFGIYEEHKJSEYEYGUGTGUFLISJPEEKNGSISGTFWFGGUIDGHGMEMIMFGJTGSIDGLIEJSKOJYGSGOKKKPGUFPHKJEEEIMGMETKOGUHSEEISEYJNETJSGSENKNKSKTGOEEIDHKFEEHKTFLJNFYFGBKFPEOFWEYFEFWEMDYFTCXJYJOKPIDFYFGHDFDIMGLENFPHTIDISHTIEECFDENHDISGTHGFPGRIMJLFXJTESJPESGOIMENJKGTJYKKHDGRGHJEGLEOFDFPHSHKFEGTFEFLGRKNGOETEOENIOJEKSIAFGEMGDGOGHEOFWIOGTGOIMETGRGDJNGOEEEEEMJEKNJLEHJTHSGTIHJYJEKKHGGLGMJLFWHSJOIYFPIDJSHGJSGOKPKNGYBKUTMWDERY',
      ];
      final decoder = URDecoder();
      int receivedCount = 0;
      for (final part in urParts) {
        final received = decoder.receivePart(part);
        if (received) {
          receivedCount++;
        }
        print('조각 수신: $received, 진행률: ${decoder.estimatedPercentComplete() * 100}%');
      }

      // 완성 여부 확인
      expect(decoder.isComplete(), true, reason: '모든 조각이 모이면 완성되어야 함');
      expect(decoder.isSuccess(), true, reason: '디코딩이 성공해야 함');

      // 디코딩 결과 text를 기대함
      print('=== UR 디코딩 결과 ===');
      final textResult = UrBytesConverter.convertToText(decoder.result);
      print(textResult);
      print('========================');
    });
  });

  group('Signer Decoder(HWW export pub key)', () {
    test('[keystone] UR:CRYPTO-ACCOUNT를 올바르게 파싱하는데 테스트', () {
      final urParts = [
        'UR:CRYPTO-ACCOUNT/OEADCYOTPRWMJOAOLYTAADMETAADDLOLAOWKAXHDCLAOGUBYCFTLBNBNLGFLHFBEZECHNSECAAONCXHYPFAMFNCSVDJYSBRSECGEGUDEHEYKAAHDCXFTCYJEFLWSOXWMIHRPIMYACLLPURCYSSIOSEIOSOSPRFUYJZVDKKBEDWLYCKIHDKAHTAADEHOEADAEAOAEAMTAADDYOTADLOCSDYYKAEYKAEYKAOYKAOCYOTPRWMJOAXAAAYCYGHIELYGEVEATAHFR',
      ];
      final decoder = URDecoder();
      int receivedCount = 0;
      for (final part in urParts) {
        final received = decoder.receivePart(part);
        if (received) {
          receivedCount++;
        }
      }
      expect(decoder.isComplete(), true, reason: '모든 조각이 모이면 완성되어야 함');
      expect(decoder.isSuccess(), true, reason: '디코딩이 성공해야 함');

      // 디코딩 결과 Map을 기대함
      print('=== UR 디코딩 결과 ===');
      final mapResult = UrBytesConverter.convertToMap(decoder.result);
      print(jsonEncode(mapResult));
      print('========================');
    });

    test('[Jade] UR:CRYPTO-ACCOUNT 조각을 올바르게 파싱하는데 테스트', () {
      final urParts = [
        'UR:CRYPTO-ACCOUNT/2-6/LPAOAMCSKPCYTKSAWPHEGHIHINEHSNZOLFOYPTFYTTDPSEYNNLKSZTMNSBUOTPBBRHFESS',
        'UR:CRYPTO-ACCOUNT/3-6/LPAXAMCSKPCYTKSAWPHEGHFXISDAPLUEZMMEMOWEFMPDFRAAHDCXHPWFPRHKYANBREBSSP',
        'UR:CRYPTO-ACCOUNT/4-6/LPAAAMCSKPCYTKSAWPHEGHFRFPRTCMEYBTWEHSZEBKYKPEBYJOHGCSQZTLTOGLNSWZIYEC',
        'UR:CRYPTO-ACCOUNT/5-6/LPAHAMCSKPCYTKSAWPHEGHJKZTAXSGSPGRSFAMTAADDYOTADLOCSDYYKAEYKAEOYWSRYRD',
        'UR:CRYPTO-ACCOUNT/6-6/LPAMAMCSKPCYTKSAWPHEGHYKAOYKAOCYMOJNNYINAXAAAYCYLACESGAYAEAEAEGYRKDSDM',
        'UR:CRYPTO-ACCOUNT/7-6/LPATAMCSKPCYTKSAWPHEGHWDRFTAGLMSUOFDIHOLTDSSNTSOYTHNLKFWLGCYGTPLRPBTEH',
        'UR:CRYPTO-ACCOUNT/8-6/LPAYAMCSKPCYTKSAWPHEGHTEAXVYHSFHWSHLOYRTWPLYWZVSFPFYJNKPKKLPCXISVLUYCW',
        'UR:CRYPTO-ACCOUNT/1-6/LPADAMCSKPCYTKSAWPHEGHOEADCYMOJNNYINAOLYTAADMETAADDLOXAXHDCLAXDSLDLBLN',
        'UR:CRYPTO-ACCOUNT/2-6/LPAOAMCSKPCYTKSAWPHEGHIHINEHSNZOLFOYPTFYTTDPSEYNNLKSZTMNSBUOTPBBRHFESS',
      ];
      final decoder = URDecoder();
      int receivedCount = 0;
      for (final part in urParts) {
        final received = decoder.receivePart(part);
        if (received) {
          receivedCount++;
        }
      }
      expect(decoder.isComplete(), true, reason: '모든 조각이 모이면 완성되어야 함');
      expect(decoder.isSuccess(), true, reason: '디코딩이 성공해야 함');

      // 디코딩 결과 Map을 기대함
      print('=== UR 디코딩 결과 ===');
      final mapResult = UrBytesConverter.convertToMap(decoder.result);
      print(jsonEncode(mapResult));
      print('========================');
    });

    test('[Coldcard] BBQR 조각을 올바르게 파싱하는지 테스트', () {
      final bbqrParts = [
        "B\$2J0301EIWAUIBAEJYDE43IL5YDE53TNARDUIBCLFYHKYRWNNKUEU2FLJTHGSRRMFCUEVCSIVUXGNLTJVZUMQ3QMFGEO23LNNTGI5TWKJSEKNRRJYZHSQRRMRRTIZTKK5FDKWT2LIZVKNTGLI3WGNKMMFCTEZTWNNWWCMLJHE3VC6TSHFBDQZDBNFCVCRDFPBAUGVRSKJHHE2SXGR3EIUSLJYRCYCRAEARHAMTTNBPXAMTXONUF6ZDFONRSEORAEJZWQKDXONUCQ43POJ2GKZDNOVWHI2JIJUWFWZJWMYYTGZDDGIXTIODIF4YGQLZQNAXTC2C5PBYHKYRWIVVHCMKMIFFTSZLVNF4EWNTWKRUGGVLRINJHOSZUKBSDO3RVMZJUM3JSNF4TIZSGMFYGOVTKIZKTGY2CMZQXKM3WNI4FUMZXIRCW4U2FKBJVCY2MGVJGQR3GHBTEEZTRIRRUCZ3SOV4GQULSHBAXIQ2ZIZ3FQRCYME3HOWSIGQXTALZKFQXC4LRJFEUSELAKEAQCE4BSO5ZWQX3EMVZGS5RCHIQCE3JPGQ4GQLZQNAXTA2BPGJUCELAK",
        "B\$2J0302EAQCE4BSO5ZWQIR2EARFU4DVMI3TKSSTNJ2UKYRRPFNDIODNKJJUIS2WPF5GS32HMVVE25LQK5MDK4SKHA3G22LFLBLWC2BRG5STM5DSO5ITQOLRNZZWCVTEKFYVQTTWGFGFITKXHF5HUNTWOVVXMZLOIQ4EMZLRPFEHUZKHLFFG6V2VG5KEO3TPGNYFOYRSGF3VKIRMBIQCAITQGJ3XG2C7MRSXGYZCHIQCE53TNAUHG33SORSWI3LVNR2GSKCNFRNWKNTGGEZWIYZSF42DQ2BPGBUC6MDIF4ZGQXLYOB2WENSFNJYTCTCBJM4WK5LKGFRHG4DCO5KGW22VI5KGEMJSNNUXK4SWNBXVE6SIMZREITTPGZYVARTVLBREIZ3JOBRGGZTKJZVW2SCHOJAXQYRZNU4GG33LJJIHAQJSOV3UWUDEMZZUKTCXNVUFA32ZO5DDCVLRMNIHIVCRGJWUG5BUF4YC6KRMFYXC4KJJEIWAUIBAEJQWGY3POVXHIIR2EARDAIRMBIQCAITYMZYCEORAEJCTMRRRGNCEGMRCBJ6QU",
        "B\$2J0300PMFCAIBCOAZHG2C7MRSXE2LWEI5CAITNF42DK2BCFQFCAIBCOAZHG2BCHIQCE6DQOVRDMOLBPA3VSRTCMRAVSQ3VJZTEU4DIKFJWU4RVLJWTE43DI5JGM2TXKV3U2U3VKA4TQUCYOJRWKULLJVLXUTCXJRFWMNT2JJVFKYTPKBBUIQSVM55G2VSYHF2UQ6KTNJ3EQZ3BHBEG25CEMY4DMQ3XNBHDMQLHGNGTOVSGNI2TG6JCFQFCAIBCOAZHG2C7MRSXGYZCHIQCE43IFBZW64TUMVSG25LMORUSQTJMLNSTMZRRGNSGGMRPGQ2WQXLYOB2WENRZMF4DOWKGMJSECWKDOVHGMSTQNBIVG2TSGVNG2MTTMNDVEZTKO5KXOTKTOVIDSOCQLBZGGZKRNNGVO6SMK5GEWZRWPJFGUVLCN5IEGRCCKVTXU3KWLA4XKSDZKNVHMSDHME4EQ3LUIRTDQNSDO5UE4NSBM4ZU2N2WIZVDKM3ZF4YC6KRMFYXC4KJJEIWAUIBAEJYDE43IL5YDE53TNBPWIZLSNF3CEORAEJWS6NBYNAXTA2BPGBUC6MLI",
      ];

      final decoder = BbQrDecoder();

      // 각 조각을 받아서 처리
      for (final part in bbqrParts) {
        final received = decoder.receivePart(part);
        expect(received, true, reason: '조각이 올바르게 수신되어야 함: $part');
      }

      // 완성 여부 확인
      expect(decoder.isComplete, true, reason: '모든 조각이 모이면 완성되어야 함');
      expect(decoder.expectedTotal, 3, reason: '총 1개의 조각이 있어야 함');
      expect(decoder.receivedCount, 3, reason: '1개의 조각이 수신되어야 함');
      expect(decoder.progress, 1.0, reason: '진행률이 100%여야 함');

      // 디코딩 결과 확인
      print('=== BBQR 디코딩 결과 ===');
      final resultJsonString = decoder.getCombinedJsonString();
      print(resultJsonString);
      print('========================');
    });
  });
}
